### ISSUE TITLE
Optimize Chip

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1124]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=10370%3A49294&t=siEMKepaonFnEEmr-1

**Comment by wueestd** [comment]
please review @Cian77

**Comment by Cian77** [comment]
See comments on page

**Comment by wueestd** [comment]
thanks for the comments, I worked it trough. could you please have another look at it @Cian77 ?

**Comment by wueestd** [comment]
Input Rouven: Dark mode

**Comment by wueestd** [comment]
could you please check the Figma implementation and the accessibility requirements @Cian77 🙏

**Comment by gfellerph** [comment]
- [ ] Discuss component variant name

**Comment by Cian77** [comment]
@rouvenpost AX-Check nötig

**Comment by wueestd** [comment]
- [ ] how big has the click are to be?

**Comment by wueestd** [comment]
@gfellerph review differences

**Comment by gfellerph** [comment]
@oliverschuerch, @alizedebray, @imagoiq please take over.

**Comment by imagoiq** [comment]
Here are the differences between the [`Chip` component](https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=10370%3A49289&mode=dev) and his sibling, the [`Badge` component](https://next.design-system.post.ch/?path=/docs/components-badge--default).

# Architecture
* Missing a notion of set or radio group (aka "Filter")
* Disabled state should be implemented

# Filter type styles to change

## General
* Gap between items should be 8px
* Line-height should use 150% instead of 100%

## Per variant

### Big/default
* Font should use $font-size-regular (16px) instead of 15px
* Padding vertical should be 8px instead of 0

### Small
* Font should be 12px instead of 13px
* Padding horizontal should be 12px instead of 7px
* Padding vertical should be 7px instead of 8px

### Hover
* Background should be Black/20% #ccc
* Border should black-60 and size 2px

### Disabled and not selected
* Border should be black-20 and 2px size
* Background should be white
* Font-color should be black-40

### Disabled and selected
* Font color should be black-40
* Border should be black-20 and 2px size
* Background should be background-dark

### Focused
* Font color should be black
* Background should be black-20

### Counter/nested badge

#### Every variant
* Counter font color should be black

#### Big
* Counter has an unneeded negative margin
* Counter font size should be 12px not 10px (10px is for small variant)
* Counter Height should be 24px instead of 22px
* Counter should not have vertical padding
* Counter horizontal padding should be 8.5px

#### Small
* Gap between icon and text should be 6px not 12px
* Counter has an unneeded negative margin
* Counter Height should be 16px instead of 22px
* Counter should not have vertical padding
* Counter horizontal padding should be 5px

#### Hover
* Border should be border black-60 and 2px size
* Counter should not have a border
* Counter should have a white background

#### Focus
* Similar to default focused state
* Counter should be similar to counter hover state

#### Disabled and not selected
* Similar to "Disabled and not selected"
* Counter background should be background-dark

#### Disabled and selected
* Similar to "Disabled and selected"
* Counter background should be white

# Input type styles to change

* Dismissible action should be before the text
* Click area from dismissible action should be 44px instead of 24px
* Gap between items should be 8px
* Icon should come from post
* Icon should have black-80% color
* Padding-start of the icon should be 8px
* Icon should not have negative margin

## Per variant

### Small
*Icon size should be 16px

### Hover
*Round background with black-20

### Focused
*Same as hover state
*Border + outline similar as other Filter variants

**Comment by imagoiq** [comment]
Dev changes: https://github.com/swisspost/design-system/issues/1864

**Comment by wueestd** [comment]
UX tasks: 

- [ ] write a documentation for the component
- [ ] publish the component
