### ISSUE TITLE
Component: Slider

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1961]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16545%3A53351&mode=design&t=UhNqX9sEMKDoYiIW-1

old
https://www.figma.com/file/KDAqx5qYIhMt5YnB7HJVSE/post_library_atoms?type=design&node-id=0%3A971&mode=design&t=3AC7rWArgkfhvKj8-1

**Code**
https://next.design-system.post.ch/?path=/docs/components-range--docs
https://design-system.post.ch/#/bootstrap-samples/form-range

**Doc**
https://www.experience-hub.ch/document/2803#/atoms-basis-elemente/controls/slider

**Comment by gfellerph** [comment]
Review is done, I think we need to discuss with the dev team about double value sliders because the single variant is easy to implement with html + css, the double valued needs to be a web component.
- Discuss how we want to release or document double valued range sliders in figma
- Adress comments in figma

**Comment by wueestd** [comment]
created the following tickets:
- https://github.com/swisspost/design-system/issues/2242
- https://github.com/swisspost/design-system/issues/2243

**Comment by gfellerph** [comment]
I updated the component tracker board (https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=14098527) and created a dev task https://github.com/swisspost/design-system/issues/2297
