### ISSUE TITLE
Component: Slider (Range)

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2242]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16545%3A53351&mode=design&t=Q7MUVh3G2mYSJ7OV-1

**Story Book:**

**Comments:**
Check if everything is there and complete component

-----------
Would be nice to keep some form of step indicators when the slider is in stepper mode (can also be floating or stepless):
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=18342%3A19436&mode=design&t=uifEJnZ0BgliN7Do-1

![Image](https://github.com/swisspost/design-system/assets/20660048/8118a04e-011d-4f17-bd20-c5c733cf20a5)

**Comment by rouvenpost** [comment]
Design ready for Review

**Comment by rouvenpost** [comment]
Design is ready for Dev.

**Comment by oliverschuerch** [comment]
@rouvenpost it is not clear to me, what really should be done in development?
- Do we want range slider (needs to be implemented through a js-based component, because there is no native behaviour like this in the input[type="range"])?
- Don't we want step indicators to show up, because the regarding figma design defines this behaiour as deprecated?

**Comment by rouvenpost** [comment]
@oliverschuerch  Yes we need this component. It is used widely...

**Comment by oliverschuerch** [comment]
@gfellerph I'm returning this review to you, because it's not clear to me, if we need the mentioned step-indicators.
Please clearify!

**Comment by gfellerph** [comment]
Won't do for v1 - will create new ticket for v2
