### ISSUE TITLE
Intranet Navigation with second level navigation on mobile breakpoints should be improved

### ISSUE THREAD

**Issue by walserthomas** [swisspost/design-system#2522]
If the intranet navigation component is used with second level navigation entries like in the Swiss Post Design System documentation. The entry are shown als dropdowns on mobile breakpoints and look very odd:

<img width="625" alt="image" src="https://github.com/swisspost/design-system/assets/157367535/39340169-48e6-4025-bf47-2760bb99b1a8">

**Comment by gfellerph** [comment]
@walserthomas thanks for submitting this issue! It's not ideal how it looks at the moment, but the component has been flagged for replacement for some time now. We will completely re-write it and make the mobile menu behave the same as for Internet applications for a better experience.

Because of this, we're not investing a lot of time to fix the Design or behaviour of the current implementation. The architecture of this component (the projects have control over whether the submenu dropdown is overlapping the flyout or that it's being cut and users need to scroll, while the Design System Team has control over the container) makes it hard to do simple changes. Another reason to rebuild it.

For these reasons, I'll close the ticket for the time being. If you disagree or have more input, please feel free to re-open.
