### ISSUE TITLE
Should we use chromatic for visual regression tests?

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2904]
Percy is basically working, but we're discovering regressions only before a release (due to low screenshot quota). Would chromatic be an option for us?

**Comment by imagoiq** [comment]
Pricing
* [Percy: from 199$/month (10'000 screenshots)](https://www.browserstack.com/accounts/subscriptions?product=percy&ref=percy)
* [Chromatic: from 349$/month (including other browsers than chrome). Same company behind Storybook, so it helps to finance the tool.](https://www.chromatic.com/pricing)

Arguments against Percy
* No HCM support
* [Some strange differences recently with accordion and Safari.](https://github.com/swisspost/design-system/issues/2960) The issue was not visible in the percy snapshots.
* Issues with web components, icons and timeout…

Alternative
* [From Cypress docs](https://docs.cypress.io/guides/tooling/visual-testing#Tooling):
  * [Happo: from 128$/month (10'000 screenshots) ](https://happo.io/pricing)
  * [Apptools: from ?](https://applitools.com/)
* Local visual testing with playwright (as it supports Webkit, which is not the case with Cypress).

**Comment by gfellerph** [comment]
@gfellerph create a POC ticket for chromatic

**Comment by gfellerph** [comment]
yes
