### ISSUE TITLE
Add tailwind output target for tokens

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3514]
Test if we can transform tokens to a tailwind config with https://github.com/nado1001/style-dictionary-tailwindcss-transformer.

This output target would be used by the Post Portal and potentially other tailwind users.

**Comment by oliverschuerch** [comment]
This could be something the post portal team could provide through a PR to the design system themselve, because no one else will probably use this output in the near future.
Or they could use our `tokens.json` output and build the desired tailwind output completely independent from the design system.

**Comment by gfellerph** [comment]
**Resolution**: Export json only, transformation to config will need to be done on portal side.
