### ISSUE TITLE
[bug]: Tooltip shown for short period of time when loading a page

### ISSUE THREAD

**Issue by juliandanis** [swisspost/design-system#3749]
**Describe the bug**
Tooltip is shown for a short period of time when loading & reloading a page.

**To Reproduce**
Go to Design System docs
Open the Tooltip page
Look at the button while loading the page

**Expected behavior**
Tooltip shouldn't be shown

**Screenshots**
https://github.com/user-attachments/assets/a6e86a89-4473-4108-8e85-b851590d39a8

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 11

Contact julian.danis@post.ch for more info

**Comment by gfellerph** [comment]
For implementation: Needs to be fixed for v8, for v9 we'll switch to attribute based hydration handling.

**Comment by oliverschuerch** [comment]
The problem exists, because we've implemented the `hydrated` class in our docs on the web-component manually.
Instead, the class should not be part of the component DOM, because it will be added by the web-component logic, as soon as the component has been hydrated.

**Any project defining the `hydrated` class statically on one of our web-components, can fix the bug, by simply removing the class.**

We're about to change the hydrated flag implementation in both packages `design-system-components` and `internet-header` in the next major release. Therefore it will be added through an `attribute`, instead of a `class`.
In the meantime, we will change the hydrated flag implementation for the `design-system-components` package already for the current version (v8) to fix this issue. Although some projects could end up with broken e2e tests, because of this.
