### ISSUE TITLE
Stepper: final step breaks with lengthier words

### ISSUE THREAD

**Issue by Gabko14** [swisspost/design-system#3977]
Hello Design System Team and @alizedebray @oliverschuerch 

I have a problem regarding the stepper. The last element seems to have less capacity to handle lengthy words like "Zusammenfassung" for example.

Screenshot:
![Image](https://github.com/user-attachments/assets/da7e63da-e441-4008-9832-f4684bed0d11)

Adding a word break could technically fix this, but it is not the desired approach. I also cannot make the whole stepper wider because there is no space.

This worked well with the ngb-progressbar implementation.

Thank you for your help

**Comment by gfellerph** [comment]
Tried to reconstruct how it looked with the `ngb-progressbar` in older versions, but was not really able to produce a desirable result:

v5
![Image](https://github.com/user-attachments/assets/b5125d02-71c2-4354-a252-63c1dd3e1716)
https://6401b58ebf0f4e298ee2dbe7--swisspost-web-frontend.netlify.app/#/post-samples/stepper

v8
![Image](https://github.com/user-attachments/assets/f8a1a219-0cfb-412a-aceb-47db2a1a375d)
https://archive.design-system.post.ch/#/post-samples/stepper

Do you have a screenshot of how you'd expect it to look and what version of the Design System are you on?

From my point of view, the only two options would be truncation (adding three dots and cutting the word like "Zusammen....") and breaking it to a new line. Truncation is generally not desired from an accessibility standpoint because you'd need to offer an alternative way to display the full word like adding the title attribute or a tooltip, but only when the word is too long to display fully - and that's not always easy to detect.

**Comment by Gabko14** [comment]
Thank you very much for taking your time to analyze this

v8.2.1
![Image](https://github.com/user-attachments/assets/b7463db1-73f3-422b-bb25-c89e3626c1df)

v6.2
![Image](https://github.com/user-attachments/assets/ae33ec25-2057-47fb-bf50-9f24ffd35620)

I have intentionally placed the word "zusammenfassung" in 3 different steps to showcase that it's only the last step which starts to panic once it contains a word with a few more characters than usual

**Comment by Gabko14** [comment]
My colleague found this great fix:

```
.stepper-item:last-child {
  justify-self: end;
}
```

Now it behaves exactly like the old stepper

**Comment by Gabko14** [comment]
> Now it behaves exactly like the old stepper

Never mind, I take that back. 

Although this works in our case, it produces other problems when there are fewer steps (3 for example)
