### ISSUE TITLE
Test migration in existing projects

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#531]
Test the migration instructions and @swisspost/design-system-migrations (based on #487) on at least 3 real projects.

- Are the instructions correct?
- Are the migrations doing their work and is the app still working afterwards?

**Comment by oliverschuerch** [comment]
Migrationtest with Project: kvm-app-web-client

Protocol:

- clone repo
- create clean test branche from origin/develop (test/migration-testing-design-system-4-to-5)
- `nvm use 13.14.0`
- `npm install`
- `npm uninstall @ch-post-common/common-web-frontend`
- `npm install @swisspost/design-system-styles@beta`
- commit changes
- visit https://update.angular.io/?v=12.0-13.0
  `ng update @angular/core@13 @angular/cli@13`
- commit changes
- `nvm use 16.17.1`
- `npx ng update @swisspost/design-system-styles --from=4 --to=5 --migrate-only`
  > Using package manager: 'npm'
  Collecting installed dependencies...
  Found 72 dependencies.
  Migrations for package were not found.
- `nvm use 14.15.0`
- `npm install @swisspost/design-system-migrations@beta`
- commit changes
- `nvm use 16.17.1`
- `npx ng update @swisspost/design-system-styles --from=4 --to=5 --migrate-only`
  > Using package manager: 'npm'
  Collecting installed dependencies...
  Found 73 dependencies.
  ** Executing migrations of package '@swisspost/design-system-styles' **

  > As of Design System v5 backgrounds make extensive use of CSS variables, therefore the .text-auto and .bg-[color]-opacity-80 classes are deprecated.
  Migration completed.

  > https://getbootstrap.com/docs/5.0/migration/#badges.
  Migration completed.

  > https://getbootstrap.com/docs/5.0/migration/#buttons.
  Migration completed.

  > https://getbootstrap.com/docs/5.0/migration/#close-button.
  Migration completed.

  > https://getbootstrap.com/docs/5.0/migration/#forms.
  Migration completed.

  > https://getbootstrap.com/docs/5.0/migration/#rtl.
  Migration completed.
- no changes to commit :confused:
- `npm run start`
- Find & replace: `@ch-post-common/common-web-frontend/` => `@swisspost/design-system-styles/`
- Find & replace: `@swisspost/design-system-styles/cwf` => `@swisspost/design-system-styles/core`
- Find & replace: `@swisspost/design-system-styles/core'` => `@swisspost/design-system-styles/core' as post`
- Find & replace: `cwf.` => `post.`

**Comment by alizedebray** [comment]
I tested the migration on real projects and here are my feedback:

Uninstall the old packages
- It would be nice to give the command: `npm uninstall @ch-post-common/common-web-frontend @ch-post-common/common-web-frontend-intranet-header`
	
Automatic migration tool
- Potential changes must be committed before running the command, otherwise it throws an error
- I had to install the migrations package, otherwise I was getting the error "The migrations for the package were not found".
- Migrations didn't work properly: most didn't work at all and one replaced classes that shouldn't be changed
_Should we drop this feature for now?_
	
Component migration
- There is a small typo: "by your self" should be replaced by "by yourself" or "by your own"
- It would be nice to mention `ngbButtonLabel` in the NgBootstrap/Buttons section so that it's easier to find in a project

---

General remarks: 
- Overall, the migration documentation is comprehensive and easy to follow
- In order to migrate the projects I had to follow almost the same steps as described by Oliver in the comment above
- Migration schemes do not currently work in real projects - to be investigated
- It seems important to specify that the migration must be done after switching to Angular@13 and NgBootstrap@12, it would be nice to add an overview of the dependencies like https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap
- Search and replace is not documented, but is needed in most cases

**Comment by gfellerph** [comment]
@alizedebray, the reason we cannot provide the uninstall command is, the internal package names are a secret that should not be made public due to dependency confusion attacks.

**Comment by oliverschuerch** [comment]
@alizedebray Some Changes have allready been implemented in the migrations documentation before.
See: PR #590.
I marked those changes in your comment above.
Some other CRs are not 100% clear (I marked them with :o:), please feel free to include the desired changes in the corresponding branch.

**Comment by oliverschuerch** [comment]
When updating angular (for example from v12 to v13):
https://update.angular.io/?v=12.0-13.0 tells you to run the command: `ng update @angular/core@13 @angular/cli@13`
If the installation fails, because of incompatible or missing peer dependencies:

![image](https://user-images.githubusercontent.com/9716662/199003629-ee4d9e4a-1b38-4207-bb6f-8dd67ac780b2.png)

Install the missing peer dependencies first: `npm i tslib@2`
Then add the incompatible peer dependencies to the update command and use the given main versions to update to.
In the above case the command would become:
`ng update @angular/core@13 @angular/cli@13 @angular-eslint/schematics@13 @ngrx/effects@13 @ngrx/store@13`
