### ISSUE TITLE
Optimize Switch

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#801]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7777%3A33877&t=zTAKJLbklgpXEsSf-1

**Comment by wueestd** [comment]
ready for frontend review

**Comment by gfellerph** [comment]
**Switch thumb**
The smaller switch thumb on inactive switches poses an implementation problem because of the green background which would leak through. The current implementation solves the issue by using a full height thumb that covers the background in both states and on animation as well. The green background slides with the thumb instead of changing instantly.

Design:
![image](https://user-images.githubusercontent.com/1659006/203795473-e44370ec-748f-4314-a907-8497c073dfe2.png)

Implementation with smaller switch thumb:
![image](https://user-images.githubusercontent.com/1659006/203795729-e3395db2-c870-42f9-a294-055693fc435e.png)

**Colors don't match**
The design uses way darker default and hover colors.

**Accessibility**
Error message icons and focus styles should be discussed.

**Comment by gfellerph** [comment]
Dev:
- [ ] follow figma design with a transition on the background

**Comment by gfellerph** [comment]
Created https://github.com/swisspost/design-system/issues/853
